---
- name: Inventory Classification Report
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Create report
      copy:
        dest: /tmp/inventory_assessment.csv
        content: |
          Host,Classification
          aap,Canonical
          aap.example.com,Duplicate
          192.168.142.128,Duplicate
          linux-aap,Duplicate
          oldserver01,Decommission Candidate
          wronghost01,Invalid DNS
          badip01,Invalid IP
