---
- name: Inventory Assessment
  hosts: all
  gather_facts: true
  ignore_unreachable: true

  tasks:

    - name: Classification
      debug:
        msg:
          host: "{{ inventory_hostname }}"
          classification: >-
            {% if ansible_machine_id is not defined %}
            Invalid / Unreachable
            {% else %}
            Reachable
            {% endif %}
          machine_id: "{{ ansible_machine_id | default('NA') }}"
