---
- name: Add host to inventory
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Create host in main inventory
      ansible.builtin.uri:
        url: "https://192.168.142.128/api/controller/v2/hosts/"
        method: POST
        user: "admin"
        password: "admin1234"
        force_basic_auth: true
        validate_certs: false
        body_format: json
        body:
          name: "{{ hostname }}"
          inventory: 3
          variables: "ansible_host: {{ ip_address }}"
        status_code:
          - 201
      register: host_result

    - name: Show API response
      ansible.builtin.debug:
        var: host_result.json
