# =====================================
# Duplicate representations
# Same actual server (AAP VM)
# =====================================

aap ansible_host=192.168.142.128

aap.example.com ansible_host=192.168.142.128

192.168.142.128

linux-aap ansible_host=192.168.142.128

# =====================================
# Bad / stale hosts
# =====================================

oldserver01 ansible_host=192.168.142.250

wronghost01 ansible_host=doesnotexist.lab.local

badip01 ansible_host=10.255.255.254
